theme: jekyll-theme-minimal
title: Welcome to the Xiang Li's Web!
description: If you want to have any unconstrained-style and creative conversation about my research interests or academic projects with me, feel free to contact me via email (click the blue 'email' below)
title: Welcome to the Xiang Li's Web!
description: If you want to have any unconstrained-style and creative conversation about my research interests or academic projects with me, feel free to contact me via email (click the blue 'email' below)
author: Xiang Li
