<head> 
theme: jekyll-theme-minimal
title: Xiang Li's HomePage
logo: "/ppp.jpg"
description: An HCI Researcher from XJTLU & Exertion Games Lab (University of Monash).
author: Xiang Li
  <link rel="shortcut icon" href="favicon2.ico" type="image/x-icon" /> 
  <link rel="icon" href="favicon.ico" type="image/x-icon" /> 
</head>
