theme: jekyll-theme-minimal
title: Xiang Li's Personal Web!
subtitle: You are my today and all of my tomorrows, and I wish I don't know you. But l do.
description: HCI Researcher from XJTLU & Exertion Games Lab (University of Monash).
author: Xiang Li
